//! Combat tick + chase loop. Combat lives in two layers: `tick_combat`
//! is the per-tick top-of-loop call from `llm_driver` (chase, face,
//! attack); `chase_target` is the pathfinding-driven approach loop that
//! polls the target position and re-routes when it moves. The same loop
//! also powers `approach_player`, the non-combat "walk up to a character
//! and stop a polite metre short" move. Constants at the top tune both
//! the chase cadence and the attack-cooldown derived from animation data.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::{Duration, Instant};

use onlinerpg_shared::{ClientMessage, PlayerId};
use tokio::sync::Mutex;
use tracing::{error, info, warn};

use crate::geom::PlanarDelta;
use crate::state::SharedState;

/// Minimum distance to a monster before attacking (matches client-side threshold).
const ATTACK_RANGE: f32 = 2.0;
/// Fallback attack cooldown if animation data is unavailable.
const DEFAULT_ATTACK_COOLDOWN_MS: u64 = 1500;
/// Path to animation durations JSON (generated by tools/extract-animation-durations.mjs).
/// Relative to agent-client working directory.
const ANIMATION_DURATIONS_PATH: &str = "data/animation_durations.json";

use super::movement::{MAX_STEP_DIST, MOVE_SPEED};

/// How often to poll when waiting (no active step to send), in ms.
const CHASE_IDLE_TICK_MS: u64 = 200;
/// Maximum chase duration before giving up (seconds).
const MAX_CHASE_SECS: f32 = 15.0;
/// Give up chasing monsters farther than this from the agent. Prevents NPC
/// guards from running far off their patrol to engage distant threats.
const MAX_CHASE_DISTANCE: f32 = 20.0;
/// How far the monster must move from our last target before we re-route.
const REROUTE_THRESHOLD: f32 = 1.5;
/// Polite stop distance when walking up to another character (player or
/// NPC): close enough to talk, far enough that the models don't overlap.
const APPROACH_RANGE: f32 = 1.0;
/// Maximum approach duration before giving up (seconds). Longer than the
/// combat chase: an approach target can be anywhere inside the sight radius.
const MAX_APPROACH_SECS: f32 = 30.0;

/// Load the attack (slash1) animation duration from the shared JSON file.
/// Returns the duration as milliseconds, or the default if loading fails.
pub(super) fn load_attack_cooldown() -> Duration {
    let Ok(text) = std::fs::read_to_string(ANIMATION_DURATIONS_PATH) else {
        warn!("Could not read {ANIMATION_DURATIONS_PATH}, using default attack cooldown");
        return Duration::from_millis(DEFAULT_ATTACK_COOLDOWN_MS);
    };

    // Structure: { "combat_melee": { "slash1": 1.533, ... }, ... }
    let Ok(data) = serde_json::from_str::<HashMap<String, HashMap<String, f64>>>(&text) else {
        warn!("Could not parse {ANIMATION_DURATIONS_PATH}, using default attack cooldown");
        return Duration::from_millis(DEFAULT_ATTACK_COOLDOWN_MS);
    };

    if let Some(duration_secs) = data.get("combat_melee").and_then(|m| m.get("slash1")) {
        let ms = (*duration_secs * 1000.0) as u64;
        info!("Loaded attack cooldown from animation data: {ms}ms");
        Duration::from_millis(ms)
    } else {
        warn!("slash1 animation not found in {ANIMATION_DURATIONS_PATH}, using default");
        Duration::from_millis(DEFAULT_ATTACK_COOLDOWN_MS)
    }
}

/// Execute one combat tick: check if target is alive and in range, chase or attack.
/// Returns Some(monster_id) to keep targeting, or None if combat ended.
pub(super) async fn tick_combat(
    state: &Arc<Mutex<SharedState>>,
    monster_id: String,
) -> Option<String> {
    // Chase until in range (handles monster movement during chase)
    match chase_monster(state, &monster_id).await {
        ChaseResult::InRange => {}
        ChaseResult::Lost | ChaseResult::Error => {
            info!("Combat ended: monster {monster_id} lost or error during chase");
            return None;
        }
    }

    // Face the monster before attacking (matches web client behavior)
    {
        let mut s = state.lock().await;
        if let Some(face_cmd) = s.face_monster_command(&monster_id) {
            if let Err(e) = s.send_command(face_cmd).await {
                error!("Failed to send face-monster move: {e}");
                return None;
            }
        }
    }

    // Send attack
    {
        let mut s = state.lock().await;
        let cmd = ClientMessage::PlayerAttack {
            monster_id: monster_id.clone(),
        };
        if let Err(e) = s.send_command(cmd).await {
            error!("Failed to send attack: {e}");
            return None;
        }
    }

    Some(monster_id)
}

pub(super) enum ChaseResult {
    InRange,
    Lost,
    Error,
}

/// What a chase walks toward: a monster (stop at attack range) or another
/// character (stop at a polite conversational distance instead of standing
/// on top of them).
pub(super) enum ChaseTarget<'a> {
    Monster(&'a str),
    Player(&'a PlayerId),
}

impl ChaseTarget<'_> {
    fn position(&self, s: &SharedState) -> Option<onlinerpg_shared::Position> {
        match self {
            Self::Monster(id) => s.nearby_monsters.get(*id).map(|m| m.position),
            Self::Player(id) => s.nearby_players.get(*id).map(|p| p.position),
        }
    }

    /// The chase ends successfully within this distance of the target.
    /// The character range carries a little slack over APPROACH_RANGE so
    /// arriving at the pulled-back path goal always counts as in range.
    fn arrive_range(&self) -> f32 {
        match self {
            Self::Monster(_) => ATTACK_RANGE,
            Self::Player(_) => APPROACH_RANGE + 0.2,
        }
    }

    /// How far short of the target the path goal stops. Monsters are
    /// pathed to directly (the arrive check stops us first); characters
    /// get a pulled-back goal so a step can never land on top of them.
    fn path_pullback(&self) -> f32 {
        match self {
            Self::Monster(_) => 0.0,
            Self::Player(_) => APPROACH_RANGE,
        }
    }

    fn max_distance(&self) -> f32 {
        match self {
            Self::Monster(_) => MAX_CHASE_DISTANCE,
            Self::Player(_) => crate::state::NPC_SIGHT_RADIUS,
        }
    }

    fn max_secs(&self) -> f32 {
        match self {
            Self::Monster(_) => MAX_CHASE_SECS,
            Self::Player(_) => MAX_APPROACH_SECS,
        }
    }
}

/// Log label. `Display` rather than a `-> String` helper so the monster arm
/// keeps borrowing its id instead of allocating a copy for a log line.
impl std::fmt::Display for ChaseTarget<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Monster(id) => f.write_str(id),
            Self::Player(id) => write!(f, "{id}"),
        }
    }
}

/// Chase the monster until we're in attack range, using A* pathfinding.
pub(super) async fn chase_monster(
    state: &Arc<Mutex<SharedState>>,
    monster_id: &str,
) -> ChaseResult {
    chase_target(state, &ChaseTarget::Monster(monster_id)).await
}

/// Walk up to another character and stop APPROACH_RANGE short of them,
/// following the target if it moves. Same loop as the combat chase.
pub(super) async fn approach_player(
    state: &Arc<Mutex<SharedState>>,
    player_id: &PlayerId,
) -> ChaseResult {
    chase_target(state, &ChaseTarget::Player(player_id)).await
}

/// Chase the target until we're within its arrive range, using A*
/// pathfinding. Polls the target position every tick and re-routes when
/// it moves.
async fn chase_target(state: &Arc<Mutex<SharedState>>, target: &ChaseTarget<'_>) -> ChaseResult {
    let chase_start = Instant::now();
    let mut path_waypoints: Vec<onlinerpg_shared::pathfinding::PathWaypoint> = Vec::new();
    let mut path_index = 0usize;
    let mut last_target_x = 0.0f32;
    let mut last_target_z = 0.0f32;

    loop {
        if chase_start.elapsed().as_secs_f32() > target.max_secs() {
            warn!("Chase timeout for target {}", target);
            return ChaseResult::Lost;
        }

        let (in_range, needs_repath, target_pos, goal) = {
            let s = state.lock().await;
            let player_alive = s.self_player.as_ref().is_some_and(|p| p.health > 0);
            let Some(target_pos) = target.position(&s) else {
                return ChaseResult::Lost;
            };
            if !player_alive {
                return ChaseResult::Lost;
            }

            let player = s.self_player.as_ref().unwrap();
            let to_target = PlanarDelta::between(&player.position, &target_pos);
            let in_range = to_target.dist <= target.arrive_range();
            if to_target.dist > target.max_distance() {
                info!(
                    "Giving up chase: target {} is {:.1}m away (>{:.1}m)",
                    target,
                    to_target.dist,
                    target.max_distance()
                );
                return ChaseResult::Lost;
            }

            let target_shift =
                PlanarDelta::xz(last_target_x, last_target_z, target_pos.x, target_pos.z).dist;
            let needs_repath = path_waypoints.is_empty()
                || path_index >= path_waypoints.len()
                || target_shift > REROUTE_THRESHOLD;

            // Path goal, pulled back toward us by path_pullback so the
            // path never ends inside the target character.
            let pullback = target.path_pullback();
            let goal = if pullback > 0.0 && to_target.dist > pullback {
                let ratio = (to_target.dist - pullback) / to_target.dist;
                (
                    player.position.x + to_target.dx * ratio,
                    player.position.z + to_target.dz * ratio,
                )
            } else {
                (target_pos.x, target_pos.z)
            };

            (in_range, needs_repath, target_pos, goal)
        };

        if in_range {
            return ChaseResult::InRange;
        }

        if needs_repath {
            let result = {
                let s = state.lock().await;
                s.find_path_to(goal.0, goal.1, 0)
            };
            if result.waypoints.is_empty() {
                path_waypoints.clear();
            } else {
                path_waypoints = result.waypoints;
            }
            path_index = 0;
            last_target_x = target_pos.x;
            last_target_z = target_pos.z;
        }

        // Step toward next waypoint, subdividing long segments so the chase
        // walks at MOVE_SPEED. Fall back to a direct step toward the target
        // if A* returned no path.
        let step_dist = if path_index < path_waypoints.len() {
            let wp = path_waypoints[path_index].clone();
            let mut s = state.lock().await;
            let player = match s.self_player.as_ref() {
                Some(p) => p,
                None => return ChaseResult::Lost,
            };
            let to_wp = PlanarDelta::to_xz(&player.position, wp.x, wp.z);

            if to_wp.dist < 0.1 {
                path_index += 1;
                0.0
            } else {
                let (step_x, step_z, sd) = if to_wp.dist <= MAX_STEP_DIST {
                    path_index += 1;
                    (wp.x, wp.z, to_wp.dist)
                } else {
                    let ratio = MAX_STEP_DIST / to_wp.dist;
                    (
                        player.position.x + to_wp.dx * ratio,
                        player.position.z + to_wp.dz * ratio,
                        MAX_STEP_DIST,
                    )
                };
                let cmd = ClientMessage::player_move(
                    onlinerpg_shared::Position {
                        x: step_x,
                        y: player.position.y,
                        z: step_z,
                    },
                    to_wp.rotation(),
                    wp.floor as i8,
                );
                s.self_floor_level = wp.floor;
                if let Err(e) = s.send_command(cmd).await {
                    error!("Failed to send chase move: {e}");
                    return ChaseResult::Error;
                }
                sd
            }
        } else {
            let mut s = state.lock().await;
            match compute_step_toward(&s, target) {
                Some((cmd, sd)) => {
                    if let Err(e) = s.send_command(cmd).await {
                        error!("Failed to send chase move: {e}");
                        return ChaseResult::Error;
                    }
                    sd
                }
                None => 0.0,
            }
        };

        let travel_ms = if step_dist > 0.0 {
            ((step_dist / MOVE_SPEED) * 1000.0) as u64
        } else {
            CHASE_IDLE_TICK_MS
        };
        tokio::time::sleep(Duration::from_millis(travel_ms.max(50))).await;
    }
}

/// Return a single MAX_STEP_DIST-limited move toward the target, plus the
/// step's distance for sleep timing. Used as the fall-through when A* can't
/// return a path (e.g. target on un-pathable terrain) so the chase can still
/// inch the player closer at walk speed. Steps stop short of the target:
/// half a step inside attack range for monsters, APPROACH_RANGE for
/// characters.
fn compute_step_toward(state: &SharedState, target: &ChaseTarget) -> Option<(ClientMessage, f32)> {
    let target_pos = target.position(state)?;
    let self_player = state.self_player.as_ref()?;

    let to_target = PlanarDelta::between(&self_player.position, &target_pos);
    let stop_dist = match target {
        ChaseTarget::Monster(_) => ATTACK_RANGE - 0.5,
        ChaseTarget::Player(_) => APPROACH_RANGE,
    };
    if to_target.dist <= stop_dist {
        return None;
    }

    let target_dist = to_target.dist - stop_dist;
    let step_dist = target_dist.min(MAX_STEP_DIST);
    let ratio = step_dist / to_target.dist;
    let cmd = ClientMessage::player_move(
        onlinerpg_shared::Position {
            x: self_player.position.x + to_target.dx * ratio,
            y: target_pos.y,
            z: self_player.position.z + to_target.dz * ratio,
        },
        to_target.rotation(),
        0,
    );
    Some((cmd, step_dist))
}
